version: "3.7"
services:

  db:
    image: postgres:15
    restart: unless-stopped
    ports:
      - 5432:5432
    # volumes:
    #   - db_home:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: wwl
      # Note: These are example credentials, you MUST change these before deploying anything
      POSTGRES_USER: example_db_user
      POSTGRES_PASSWORD: example_db_password

  wwl-server:
    build:
      context: ../packages/wwl/
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8787:8787
    depends_on:
      - db
    environment:
      # Note: These are example credentials, you MUST change these before deploying anything
      DATABASE_URL: "postgresql://example_db_user:example_db_password@db:5432/wwl"
      ADMIN_AUTH_DEFAULT_EMAIL: "admin@admin.com"
      ADMIN_AUTH_DEFAULT_PASSWORD: "admin"
      ADMIN_AUTH_SESSION_SECRET: "asdfgh12345"
