import type { Migration } from "../migrate.js";

import { DataTypes } from "sequelize";

const columnComments = {
  clientResponseId:
    "An id for this response, counting up from 0 and generated by the client. It is only unique within a session and is used to avoid storing duplicates when a client re-sends a response it did not receive a confirmation for.",
};

export const up: Migration = async ({ context }) => {
  await context.addColumn("wwl_responses", "clientResponseId", {
    type: DataTypes.INTEGER,
    allowNull: true,
    comment: columnComments.clientResponseId,
  });

  // Responses without a clientResponseId keep it set to NULL and NULL values
  // are treated as distinct from one another, so old clients (which do not
  // send the field) are unaffected by this index.
  await context.addIndex("wwl_responses", ["sessionId", "clientResponseId"], {
    name: "idx_wwl_responses_sessionId_clientResponseId",
    unique: true,
  });
};
export const down: Migration = async ({ context }) => {
  await context.removeIndex(
    "wwl_responses",
    "idx_wwl_responses_sessionId_clientResponseId",
  );
  await context.removeColumn("wwl_responses", "clientResponseId");
};
