name: Create and release Electron App

on:
  # Run manually
  workflow_dispatch:
  # Run for any new tag starting with "v" e.g. "v1.2.3"
  push:
    # tags:
    #   - "v*"

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 18.16

      - name: Install root dependencies
        run: npm ci

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

          # Custom Settings
          package_root: ./electron-app
          build_script_name: build:wwl

      - name: Move Build Artifacts
        shell: bash
        run: ./electron-app/scripts/move-artifacts.sh

      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: electron-app-linux
          path: dist-linux

      - name: Upload Mac Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: electron-app-mac
          path: dist-mac

      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: electron-app-windows
          path: dist-windows
