name: Create and release Electron App

on:
  # Run manually
  workflow_dispatch:
  # Run for any new tag starting with "v" e.g. "v1.2.3"
  push:
    # tags:
    #   - "v*"

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 18.16
          cache: 'npm'

      - name: Install root dependencies
        run: npm ci

      - name: Install Electron dependencies
        working-directory: ./electron-app
        run: npm ci

      - name: Build Electron App
        working-directory: ./electron-app
        run: npm run build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: electron-app-${{ matrix.os }}
          path: |
            electron-app/dist/*.exe  # For Windows
            electron-app/dist/*.dmg  # For macOS
            electron-app/dist/*.AppImage  # For Linux
