name: Run Tests & Build
on: push
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm i
    - name: Run tests
      run: npm run test
    - name: Build the app
      run: npm run build
