name: Run Playwright Tests for Electron App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-playwright:
    timeout-minutes: 60
    runs-on: macos-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      # Temporary workaround for #72, till the issue is fixed in sqlite3 package
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install pango dependency
        run: |
          brew install pango
      # End of workaround

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Electron dependencies
        working-directory: ./electron-app
        run: npm ci

      - name: Run Electron Tests
        working-directory: ./electron-app
        run: npm run test:playwright

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: report-electron-app
          path: electron-app/playwright-report/
          retention-days: 30
