name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium
    - name: Run Playwright tests
      run: npm run test:playwright
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: report-server
        path: packages/server/playwright-report/
        retention-days: 30
    # Electron App
    # We do this in the same step, as it also needs to re-build the server,
    # so it would need to install all dependencies again)
    - name: Install dependencies (electron-app)
      run: npm ci
      working-directory: ./electron-app
    - name: Run Playwright tests (electron-app)
      run: npm run test:playwright
      working-directory: ./electron-app
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: report-electron-app
        path: electron-app/playwright-report/
        retention-days: 30
